version: '3.9'

services:
  hn-api:
    build: .
    container_name: hn-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - PYTHON UNBUFFERED=1
    restart: unless-stopped

  test:
    build: .
    command: [ "pytest", "tests/" ]
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
